name: Copy Systematik File and Move/Rename

on:
  push:
    branches:
      - main

jobs: 
  copy-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout

    - name: Copy and Move/Rename File
      run: |
        cd source
        latest_file=$(ls -t | head -n1)
        cp $latest_file ../dist/sys.xml
      shell: bash
  
    - name: Add XSL Declaration
      run: |
        cd dist
        sed -i '2i\<?xml-stylesheet type="text/xsl" href="sys.xsl"?>' sys.xml
      shell: bash

    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v4